### ISSUE TITLE
Unable to convert txt file to html

### ISSUE THREAD

**Issue by mnosov622** [sfrunza13/SiteGenerationTool#1]
Hello!

Unfortunately, when I run python Sitegen.py -i ./random.txt, I get error message saying : 

_Error: [Errno 2] No such file or directory: './dist/./random.html'
Input option:  ./random.txt
Output option:  ./dist_

But in the console I can see the converted version of the file.

**Comment by sfrunza13** [comment]
Thanks for spotting this, I just pushed a change to have the dist directory always be created now.
